//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final01._03._2021.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brendler> brendlers { get; set; }
        public virtual DbSet<orta> ortas { get; set; }
        public virtual DbSet<sati> satis { get; set; }
        public virtual DbSet<slide1> slide1 { get; set; }
        public virtual DbSet<adminlogin> adminlogins { get; set; }
        public virtual DbSet<ok> oks { get; set; }
    }
}
