//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final01._03._2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteri4
    {
        public int ID { get; set; }
        public string fotourl { get; set; }
        public string adsoyad { get; set; }
        public string unvan { get; set; }
        public int nomre { get; set; }
        public string haqqinda { get; set; }
    }
}
